version: 2.1
orbs:
  node: circleci/node@7
jobs:
  deploy:
    executor:
      name: node/default
      resource_class: small
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: mkdir -p /tmp/artifact && cp --recursive dist /tmp/artifact/ && cp package.json /tmp/artifact/
      - run: npm --dir /tmp/artifact publish
workflows:
  unit-test:
    jobs:
      - node/test:
          test-results-for: jest
          executor:
            name: node/default
            resource_class: small
  deploy:
    jobs:
      - deploy
