version: 2.1
orbs:
  node: circleci/node@7
jobs:
  deploy:
    executor:
      name: node/default
      resource_class: small
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: jq --arg ver "0.1.0" '.version = $ver' package.json > /tmp/package.json && mv /tmp/package.json package.json
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run: npm publish
workflows:
  unit-test:
    jobs:
      - node/test:
          test-results-for: jest
          executor:
            name: node/default
            resource_class: small
  deploy:
    jobs:
      - deploy:
          context: [npm]
