version: 2.1
orbs:
  node: circleci/node@7
executors:
  node:
    docker:
      - image: cimg/base
    resource_class: small
jobs:
  unit-test:
    docker:
      - image: cimg/base
    resource_class: small
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - node/test:
          test-results-for: jest
workflows:
  unit-test:
    jobs:
      - node/test:
          test-results-for: jest
          executor: node
